apiVersion: 1

datasources:
  - name: combined_weather
    uid: combined_weather_pg
    type: postgres
    access: proxy
    url: db:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      database: combined_weather
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
